# Configure main menu and social menu
 [[main]]
 identifier = "travelling"
 name = "Travelling"
 url = "https://www.travellings.cn/go.html"
 [main.params]
 icon = "train"
 newtab = true

[[social]]
identifier = "rss"
name = "Rss"
url = "/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "Email"
name = "Email"
url = "mailto:recevier0612@takuron.com"

[social.params]
icon = "mail"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/takuron"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/11680006"

[social.params]
icon = "brand-bilibili"
